### ISSUE TITLE
Creating API Gateway on AWS for Sigfox communication

### ISSUE THREAD

**Issue by jamesle-0812** [lupyuen/send_altitude_cocoos#7]
Hi there,
Can you give me a tutorial how to create a API Gateway on AWS please? I'm doing a project related to bi-directional communication with Sigfox & AWS.
Thanks in advance for your time & support!

**Comment by lupyuen** [comment]
Hi: Sorry I have closed my AWS accounts so I can't show you the steps.  But I recall that when you create an AWS Lambda function, you can select an API Gateway template, and it will configure the API Gateway settings for you.

Could you try that?

**Comment by lupyuen** [comment]
You can also check this tutorial: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-lambda.html

**Comment by jamesle-0812** [comment]
Hi, thanks for your reply. I've created a API Gateway in AWS Lambda function. I've done on configurations as your advice in Sigfox callback. However, when transferring information to data the gateway, the Sigfox callback shows an error of "502 Bad Gateway". Please have a look in the screenshoot [https://imgur.com/Akqh8p5](url)
Any suggestion? Thanks in advance!

**Comment by lupyuen** [comment]
Can you check the Sigfox callback screen: https://cdn-images-1.medium.com/max/480/1*1wzDWaToL4IXB3Ff-Js4pA.png

And check the box "Send SNI"? I think this option may be needed for AWS.

If that doesn't work, can you send me the screenshots of your Sigfox callback, as well as the AWS Lambda and API Gateway config? You can reach me at luppy@appkaki.com.

**Comment by lupyuen** [comment]
Solved by testing with a simpler Sigfox callback: https://gist.github.com/lupyuen/cdc0dd93672da5b6c44a3ae5003a32c0#file-sigfox-downlink-js
